# Generated by Django 3.1.7 on 2021-03-25 11:35

from django.db import migrations, models
import team.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=32, null=True)),
                ('last_name', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, db_index=True, max_length=32, null=True, validators=[team.utils.mobile_validator])),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('REGULAR', 'Regular')], default='REGULAR', max_length=8)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
